#!/usr/bin/env bash

hyprpick() {
  hyprpicker -a | wl-copy
}

check_dependencies() {
  ! command -v hyprpicker &>/dev/null && {
    notify-send -u critical -a "Color Picker" xcolor-pick "hyprpicker needs to be installed"
    exit 1
  }

  ! command -v convert &>/dev/null && {
    notify-send -u critical -a "Color Picker" xcolor-pick "imagemagick needs to be installed"
    exit 1
  }
}

main() {
  hyprpick || return 1
    TMPPST=$(wl-paste)
    CMD=$(echo "$TMPPST")
    TMP=/tmp/xcolor_$CMD.png

    convert -size 120x120 xc:"$CMD" "$TMP"
    printf %s "$CMD" | wl-paste

    notify-send -a "Color Picker" -i "$TMP" xcolor-pick "$CMD"
}

check_dependencies
main || exit 1
