#!/usr/bin/env bash

src=""
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}"
STATE_FILE="${STATE_DIR}/current_source"

select_source() {
  src="-p $1"
}

change_volume() {
  diff=0.05
  case $1 in
    i) playerctl $src volume "${diff}+";;
    d) playerctl $src volume "${diff}-";;
    *) ;;
  esac
  return
}

get_meta() {
  playerctl $src metadata "$@"
}

get_state() {
  playerctl $src status
}

print_state() {
  state=$(get_state)
  case $state in
    Playing) echo "";;
    Paused) echo "";;
  esac
}

get_current() {
  title=$(get_meta title)
  artist=$(get_meta artist)

  case $1 in
    update) get_meta -F -f '{{status}} {{title}} - {{artist}}' | while read line; do
      line=$(echo $line | sed -e '{s/^Playing//}')
      line=$(echo $line | sed -e '{s/^Paused//}')
      echo $line
    done;;
    *) get_meta -f '{{title}} - {{artist}}';;
  esac
}

main() {
  select_source "$(cat $STATE_FILE)"
  flag="$1"
  shift 1
  # [[ -z "$flag" ]] || select_source $flag

  case $flag in
    update)  get_current update;;
    current) echo "$(print_state) $(get_current)";;
    toggle)  playerctl $src play-pause;;
    prev)    playerctl $src previous;;
    next)    playerctl $src next;;
    select)  new="$(playerctl -l | rofi -dmenu -config "$HOME/.config/rofi/select.rasi")"
      [[ -z "$new" ]] && return
      echo "$new" > $STATE_FILE
      pgrep waybar && pkill -SIGUSR2 waybar;;
    volume) change_volume $@;;
    *) echo "";;
  esac
}

main $@
